const enUS = {
  common: {
    appName: 'Attendant',
    send: 'Send',
    ask: 'Write a message',
    themeToggle: 'Toggle theme',
  },
  sidebar: {
    simulator: 'Simulator',
    settings: 'Attendant',
  },
  chat: {
    thinking: 'Typing',
    error: 'Could not send the message. Please try again.',
    errors: {
      text_required: 'Write a message before sending.',
      text_too_long: 'Message is too long.',
    },
    commands: {
      title: 'Commands',
      placeholder: 'Write as a customer or type / for commands',
      reset: {
        label: '/reiniciar',
        description: 'Delete this test conversation and start over',
      },
    },
  },
  simulator: {
    title: 'Simulator',
    subtitle:
      'Chat as if you were a customer on WhatsApp. It is the same attendant that answers there.',
    empty: 'Send a "hi" to start.',
    loadError: 'Could not load the test conversation.',
    resetDone: 'Conversation deleted. You can start over.',
    resetError: 'Could not delete the conversation.',
    provider: {
      persona: 'Fixed persona text',
      agent: 'Generated by AI',
    },
  },
  settings: {
    title: 'Attendant',
    subtitle: "Set the attendant's persona, gender and languages.",
    identity: {
      title: 'Identity',
      subtitle: 'Name and gender the bot introduces itself with.',
    },
    name: {
      label: 'Bot name',
      placeholder: 'E.g.: Nina',
      hint: 'Shown in the greeting. Up to 60 characters.',
    },
    gender: {
      title: 'Gender',
      subtitle: 'Sets the agreement used in the texts the bot writes.',
      neutral: {
        title: 'Neutral',
        description: 'No marking: "atendente virtual".',
      },
      female: {
        title: 'Female',
        description: 'Feminine agreement: "a atendente virtual".',
      },
      male: {
        title: 'Male',
        description: 'Masculine agreement: "o atendente virtual".',
      },
    },
    personality: {
      title: 'Personality',
      subtitle:
        'The attendant\'s tone: applies to the fixed texts (greeting, "didn\'t understand") and to the AI replies.',
      friendly: {
        title: 'Friendly',
        description: 'Warm and approachable, informal language.',
      },
      formal: {
        title: 'Formal',
        description: 'Courteous and impersonal, no slang.',
      },
      objective: {
        title: 'Objective',
        description: 'Straight to the point, no preamble.',
      },
      technical: {
        title: 'Technical',
        description:
          'Precise; asks for missing details (items, quantities, address).',
      },
    },
    languages: {
      title: 'Languages',
      subtitle: 'Languages the attendant uses with customers.',
      active: 'Active',
      locked: 'Only language available for now.',
      'pt-BR': {
        label: 'Portuguese (Brazil)',
        description: "The attendant's default language.",
      },
    },
    preview: {
      title: 'Preview',
      subtitle:
        'How the bot talks with the saved configuration. Updates on sync.',
      greeting: 'Greeting',
      identity: 'When asked who it is',
      fallback: 'When it cannot help',
      junk: "Didn't understand",
    },
    scope:
      'Greeting, identity and "didn\'t understand" come from these fixed texts, without AI. The rest of the conversation is AI, following the same tone.',
    sync: {
      pending: 'Unsaved changes...',
      syncing: 'Saving...',
      synced: 'Saved',
    },
    loadError: 'Could not load the attendant configuration.',
    errors: {
      generic: 'Could not save. Please try again.',
      name_required: 'Enter the bot name.',
      name_too_long: 'The bot name is longer than 60 characters.',
      unknown_personality: 'Invalid personality.',
      unknown_gender: 'Invalid gender.',
      languages_required: 'Select at least one language.',
      unsupported_language: 'Language not yet supported by the backend.',
    },
  },
  login: {
    title: 'Admin area',
    subtitle: "Sign in to access the attendant's admin panel.",
    email: 'Email',
    emailPlaceholder: 'you@company.com',
    password: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in...',
    logout: 'Sign out',
    // One key per code returned by the backend. `generic` covers a new code
    // the frontend does not know yet — t() would otherwise return the raw key.
    errors: {
      generic: 'Could not sign in. Please try again.',
      invalid_credentials: 'Invalid email or password.',
      rate_limited: 'Too many attempts. Please wait a moment.',
      network: 'Connection failure with the server.',
      session_expired: 'Your session has expired. Please sign in again.',
    },
  },
  account: {
    menuLabel: 'Account menu',
    signedInAs: 'Signed in as {email}',
    tenantLabel: 'Company',
    settingsItem: 'Settings',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Preferences for your admin session.',
    close: 'Close',
    language: {
      title: 'Interface language',
      subtitle: 'Sets the language of the admin panel.',
      'pt-BR': 'Portuguese (Brazil)',
      'en-US': 'English (US)',
    },
  },
} as const;

export default enUS;
